- name: copy rabbitmq.repo file to remote machine 
  ansible.builtin.copy: 
    src: rabbitmq.repo 
    dest: /etc/yum.repos.d/rabbitmq.repo 

- name: install rabbitmq 
  ansible.builtin.package: 
    name: rabbitmq-server 
    state: present 

- name: start rabbitmq as service 
  ansible.builtin.service:
    name: rabbitmq-server 
    state: started 
    enabled: yes 

- name: create rabbitmq user 
  community.rabbitmq.rabbitmq_user:
    user: roboshop 
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present   