- name: app setup will be done from here 
  include_role: 
    name: common 
    tasks_from: app-setup 

- name: nodejs-setup will be done from here 
  include_role: 
    name: common 
    tasks_from: nodejs-setup 

- name: copying mongo.repo file to a remote location 
  ansible.builtin.copy: 
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongo.repo 

- name: install mongodb client 
  ansible.builtin.dnf: 
    name: mongodb-mongosh 
    state: present 

- name: products loaded or not 
  ansible.builtin.command: mongosh --host mongodb.deepthi.tech --eval 'db.getMongo().getDBNames().indexOf("catalogue")' 
  register: dataload_output 

- name: print output 
  ansible.builtin.debug: 
    msg: "{{ dataload_output }}" 

- name: load products 
  ansible.builtin.shell: mongosh --host mongodb.deepthi.tech </app/db/master-data.js
  when: dataload_output.stdout | int < 0 

- name: systemd-setup will be done from here 
  include_role: 
    name: common 
    tasks_from: systemd-setup 