- name: install python3 packages 
  ansible.builtin.dnf: 
    name: "{{ item }}"
    state: installed   
  loop: 
  - python3   
  - gcc 
  - python3-devel 

- name: install dependencies 
  args: 
    chdir: /app 
  ansible.builtin.pip:  
    requirements: requirements.txt 
    executable: pip3.9 
